sudo: false
language: node_js
node_js:
  - "8"
  - "10"
install:
  npm install
script:
  - npm test -- --coverage # Include coverage when running tests
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: react
