sudo: false
language: node_js
node_js:
  - "10"
install:
  npm ci
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  local-dir: build
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: react
    if: tag IS present
