name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: configuring git user to deploy
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/belchior/clone-2048.git

      - name: npm install, test, build and deploy
        run: |
          npm ci --no-optional
          npm run test
          npm run deploy

      - name: collecting code coverage
        run: |
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} npm run coveralls
